name: build and deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: install operating system dependencies
        run: npx playwright install-deps chromium

      - name: install and build
        run: |
          npm ci
          npm run build

      - name: collect benchmarks
        run: node src/collect-benchmarks.js

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: dist
